name: Quality
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        
    - name: Checkout code
      uses: actions/checkout@v3
            
    - name: Run Unit tests
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...
        
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
      
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: covprofile
